### ISSUE TITLE
Header key collision

### ISSUE THREAD

**Issue by airidasj** [pravdomil/express-php-fpm#1]
Hi,

I'm gettiing the following, when setting up the demo instalation:

masterclass$ node server.js
/Users/masterclass/Desktop/testingSubdomains/server.js:51
  env: {'Content-Type', 'application/json'},
                      ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

node -v
v8.4.0

php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

server.js:

const express = require('express')
const epf = require('express-php-fpm')

const options = {
  // root of your php files
  documentRoot: __dirname + '/php_files',

  // extra env variables
  env: {},

  // connection to your php-fpm server
  // https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener
  socketOptions: { port: 9000 },
}

const app = express()
app.use('/', epf(options))
app.listen(3000)
console.log("Server listening!");

package.json:

{
  "name": "testingsubdomains",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.15.4",
    "express-php-fpm": "0.0.32",
    "express-subdomain": "^1.0.5",
    "express-subdomain-router": "^1.0.3",
    "node-php": "0.0.1",
    "path": "^0.12.7",
    "subdomain": "^1.2.0"
  }
}

(Running on MAC OSX, tried to test if fpm is working, so when I launch php-fpm <path/to/file> it prints out file contents...

**Comment by kenlo88** [comment]
switch to express@4.14.0, this works for me in many php applications but still fails in adminer-4.3.1-mysql.php

**Comment by kenlo88** [comment]
A small patch solves it all.  Add this line before line 134 of index.js
for (var zz in headers) { headers[zz] = headers[zz].toString(); }

**Comment by pravdomil** [comment]
fixed https://github.com/pravdomil/express-php-fpm/commit/61e4212321b2d3847cf01ded236065c439687e1a
